version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: ./app/dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./app:/go/src/app
    ports:
      - "8080:8080"
    depends_on:
      - "db"
  db:
    build:
      context: .
      dockerfile: ./db/dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - web-dev-data:/var/lib/mysql
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "33306:33306"
volumes:
  web-dev-data:
    driver: local